version: '3.8'

services:
  api:
    image: api
    build:
      context: ./backend/api
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend/api:/api
    networks:
      - my_network
    command: ["poetry", "run", "uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  app:
    image: app
    build:
      context: ./frontend/app
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend/app:/app
    networks:
      - my_network
    command: ["npm", "run", "dev"]

networks:
  my_network:
    driver: bridge
